spring:
  config:
    import: optional:file:.env[.properties]
  cloud:
    gateway:
      routes:
        - id: register-route
          uri: ${AUTHN_URI}
          predicates:
            - Path=/api/v1/users
            - Method=POST
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 2  # requests per second
                redis-rate-limiter.burstCapacity: 4  # maximum requests can be done in parallel
                key-resolver: "#{@ipKeyResolver}"
        - id: activation-route
          uri: ${AUTHN_URI}
          predicates:
            - Path=/api/v1/users/activation
          filters:
              - name: RequestRateLimiter
                args:
                    redis-rate-limiter.replenishRate: 1  # requests per second
                    redis-rate-limiter.burstCapacity: 2  # maximum requests can be done in parallel
                    key-resolver: "#{@ipKeyResolver}"
        - id: other-authentication-service-routes
          uri: ${AUTHN_URI}
          predicates:
            - Path=/api/v1/users/**
        - id: authn-api-docs-route
          uri: ${AUTHN_URI}
          predicates:
            - Path=/authn/v1/api-docs
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: ${CORS_ALLOWED_ORIGINS}
            allowedMethods: ${CORS_ALLOWED_METHODS}
            allowedHeaders: ${CORS_ALLOWED_HEADERS}
            allowCredentials: ${CORS_ALLOW_CREDENTIALS}
            maxAge: ${CORS_MAX_AGE}
  data:
    redis:
      host: localhost
      port: 6379
      password: ${REDIS_PASSWORD}
server:
  port: 8000
springdoc:
  api-docs:
    enabled: true
    path: /v1/api-docs
  swagger-ui:
    enabled: true
    config-url: /v1/api-docs/swagger-config
    urls:
      - name: gateway-service
        url: /v1/api-docs
      - name: authn-service
        url: /authn/v1/api-docs